### ISSUE TITLE
'Dot.png' Is using a Relative reference, Should be absolute URL?

### ISSUE THREAD

**Issue by Nhawdge** [ErikHen/ImagePointEditor#5]
Hello, Thanks for the great plugin! I found an issue where an odd redirect pointed a user to `/Episerver/Cms/home/Index`. When the dot tries to load it fails to resolve since it relies on `/Episerver/cms` and fails when `home/index` is in the URL. Not sure if this is something that can be resolved

**Comment by ErikHen** [comment]
Hey. Thanks. Not really sure what you mean. How can I reproduce this issue?

**Comment by Nhawdge** [comment]
Sorry for the late reply, The easiest way to recreate it, on any site, Load `<yourdomain>/Episerver/Cms/home/Index` and you'll see the dot.png can no longer be properly referenced.

**Comment by ErikHen** [comment]
Ok, now I understand the issue. 
Using an absolute path is not possible because not all solution use the standard "/episerver/...". But I will look into it and see if there is a good solution.

**Comment by ErikHen** [comment]
Version 1.0.1 contains a fix for this.
