### ISSUE TITLE
Modules folder not copied to output

### ISSUE THREAD

**Issue by Dandroid5000** [ErikHen/ImagePointEditor#9]
Hi,

When I run commands such as dotnet run, dotnet build, dotnet watch or dotnet publish, the modules folder (modules/_protected/ImagePointEditor) is not copied to the output (/bin/Debug/net5.0/modules/_protected/ImagePointEditor)

Note, if I build the solution using visual studio, the folder is created in the solution... it's just a problem using the command line.

Let me know if I'm missing something

Cheers

Dan

**Comment by ErikHen** [comment]
Hi Dan. Sorry, I'm a bit confused 😊. Are you trying to build this solution, or do you mean when you build the Episerver solution that uses this nuget?

**Comment by Dandroid5000** [comment]
Sorry for the confusion. The issue is when building a solution that uses this nuget.

**Comment by ErikHen** [comment]
ImagePointEditor.zip should be copied to \modules\_protected\ImagePointEditor when you build. That is defined in ImagePointEditor.props. 
I haven't tested building it outside of Visual Studio, maybe the .props file isn't picked up when doing dotnet build. 
You can also try and use v2.0.1, I made a small change in how the nuget was built in v2.0.2

**Comment by Dandroid5000** [comment]
Thanks. I tried v2.0.1 but having the same issue.
Yeah, it looks like the commands in the ImagePointEditor.props aren't read during the dotnet build

**Comment by mgnusl** [comment]
I am seeing the same problem. dotnet build and dotnet publish are not including any of the modules/_protected content.
Not sure if related, but the same problem occurs in my pipeline in Azure Devops, where I'm using MSBuild. The static files are not included in the published project package, resulting in 404 for imagepointproperty.js and lots of Dojo errors.

**Comment by ErikHen** [comment]
Hi. I have been able to reproduce the issue, and have tried about 236 different ways to get it to work properly 😊. I will continue trying. Meanwhile a workaround is to build it using Visual Studio and then set the zip file to be treated as content. 
  ```
<Content Include="modules\_protected\ImagePointEditor\ImagePointEditor.zip">
	<CopyToOutputDirectory>Always</CopyToOutputDirectory>
  </Content>
```
